modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/trade-cycling/issues"
[[mods]]
modId = "trade_cycling"
version = "${mod_version}"
displayName = "Trade Cycling"
updateJSONURL = "https://update.maxhenkel.de/neoforge/trade_cycling"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/trade-cycling"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''The trade cycling functionality from Easy Villagers.'''
[[mixins]]
config = "trade_cycling.mixins.json"
[[dependencies.trade_cycling]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.trade_cycling]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"